# Generated by Django 4.1.5 on 2023-02-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='bio',
            new_name='description',
        ),
    ]
