# Generated by Django 4.1.5 on 2023-02-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_bio_skill_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='socila_github',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='socila_linkedin',
            new_name='social_linkedin',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='socila_twitter',
            new_name='social_twitter',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='socila_website',
            new_name='social_website',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='socila_youtube',
            new_name='social_youtube',
        ),
    ]
